config/routes.rb
Rails.application.routes.draw do

  get 'organizations/user_index'


  root "homes#index"
  
  devise_for :users, controllers: {sessions: 'users/sessions'}


  resources :homes

  resources :admins

  resources :organizations
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord


  validates :zip_code, length: { is: 6 }

  

  def self.search(search)
  	where(%q[ org_name LIKE :keyword OR country LIKE :keyword], :keyword=>"#{search}")
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # before_action :authenticate_seller
  before_action :set_new

  def index
  	@search = Organization.ransack(params[:q])
    @search.sorts = 'org_name asc' if @search.sorts.empty?
    @search.sorts = 'org_identifier asc' if @search.sorts.empty?
    @search.sorts = 'country asc' if @search.sorts.empty?
  	organizations = Organization.order(org_name: :asc) if params[:order] == "asc"
    organizations = Organization.search(params[:search])
  	organizations = Organization.all if params[:search].nil?
    @organizations = organizations.paginate(page: params[:page]).per_page(4).order("created_at DESC")
    respond_to do |format|
      format.html
      format.json { render json: @organizations, status: :ok }
    end
  end

  def create
    @user = current_user.id
    @organization = Organization.new(organization_params)
    @organization.user_id = @user
    respond_to do |format|
      if @organization.save
        format.json {render json: @organization, status: :created}
        format.js {redirect_to root_path }
        format.html {redirect_to root_path, flash: { success: "Invoice Saved Successfully" }}
      else
        format.json {render json: @organization.errors.full_messages, status: :unprocessable_entity }
        format.js
        format.html {redirect_to invoices_path, flash: { error: @organization.errors.full_messages }}
      end
    end
  end


  def edit
  end

  def show
  end



  private

  def set_new
  	@organization = Organization.new
  end

  def organization_params
  	params.require(:organization).permit(:org_name,:org_identifier,:first_name,:last_name,:address_line1,:address_line2,:city,:state,:country,:zip_code)
  end




end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_action_buttons.html.erb
<div class="row action-button-margins">
  <div class="col-md-3">
    <%#= link_to "New Organization", new_organization_path, class: "btn btn-outline-primary"%>
  </div>
  <div class="col-md-3">
    <%= link_to "Show All", admins_path, class: "btn btn-outline-primary btn-md" %>
  </div>


  <div class="col-md-3">
          <b><%= link_to "Home",homes_path, class: "btn btn-outline-primary" %></b>

    <div class="nav">

      <% if user_signed_in? %>
                <b class="hi"> Hi! </b><%= current_user.email %>
                <b><%= link_to 'Log out', destroy_user_session_path, method: :delete %></b>
            </li>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path %>
            <%= link_to 'Sign in', user_session_path %>
      <% end %>
    </div>
  </div>

</div>

<div class="row action-button-margins">

  <div class="col-md-3">
     <%#= link_to "Org Name", organizations_path(order: "asc"), class: "btn btn-outline-primary" %>
     <%#= sort_link(@search, :org_name, "Org Name") %>
     <%= link_to 'Org Name',admins_path(order: "org_name"), class: "btn btn-outline-primary" %>

  </div>

  <div class="col-md-3">
     <%= link_to "Created By", class: "btn btn-outline-primary btn-md" %>
  </div>

  <div class="col-md-3">
     <%= link_to "Country", class: "btn btn-outline-primary btn-md" %>
  </div>

  <div class="col-md-3">
      <div class="one">
        <%= form_tag(admins_path,html: {class: 'sea'}, method: :get) do %>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "eg: search..." %> 
      </div>
        <div class="search">
            <%= submit_tag 'Search', org_name: nil ,class: "btn btn-outline-primary"%>
        </div>
      <% end %>
  </div>
</div>


<style type="text/css">
  .sea{
    width: 90%;
    float: right;
    margin-right: 71%;
  }
  .one{
    width: 100%;
    float: left;
    margin-left: -46%;
  }
   .nav{
    width: 113%;
    float: right;
    margin-right: -113%;
  }
  .hi{
    color: black;
    background-color: #94a294;
  }
</style>

app/views/organizations/_form.html.erb
        <h3 class="text-left">New Organization</h3>

        <div class="new_form">
            <%= form_for :organization, url: organizations_path,html: {class: 'org_form'}, method: :post, remote: true do |f| %>
                <div class="row">
                    <div class="col-3">
                      <%= f.label :org_name, "Organization Name:" %>
                      <%= f.text_field :org_name, class: "form-control",:id=>"textbox1"  %>
                    </div>

                    <div class="col-3">
                      <%= f.label :org_identifier, "Organization Identifier:" %>
                      <%= f.text_field :org_identifier, class: 'form-control', readonly: true, :id=>"textbox2" %>
                    </div>

                </div>

                <div class="row">

                    <div class="col-3">
                      <%= f.label :first_name, "First Name:" %>
                      <%= f.text_field :first_name, class: 'form-control' %>
                    </div>


                    <div class="col-3">
                     <%= f.label :last_name, "Last Name:" %>
                     <%= f.text_field :last_name, class: 'form-control' %>
                    </div>

                </div>

                <div class="row">

                    <div class="col-3">
                      <%= f.label :address_line1, "Address1:" %>
                      <%= f.text_field :address_line1, class: 'form-control' %>
                     </div>

                    <div class="col-3">
                      <%= f.label :address_line2, "Address2:" %>
                      <%= f.text_field :address_line2, class: 'form-control' %>
                     </div>
                </div>

                <div class="row"> 
                    <div class="col-3">
                      <%= f.label :city, "City:" %>
                      <%= f.text_field :city, class: 'form-control' %>
                    </div>

                    <div class="col-3">
                      <%= f.label :state, "State:" %>
                      <%= f.text_field :state, class: 'form-control' %>
                     </div>
                </div>

                <div class="row">
                     <div class="col-3">
                      <%= f.label :country, "Country:" %>
                      <%= f.text_field :country, class: 'form-control', :id=>'quantity' %><span id="errmsg"></span>
                     </div>

                     <div class="col-3">
                     <%= f.label :zip_code, "Zip Code:" %>
                       <%= f.text_field :zip_code, class: 'form-control', :id=>"numberonly" %>
                     </div>
                </div>
                <br>

                <div class="row">
                  <div class="actions">
                    <%= f.submit "Submit", class: 'btn btn-primary pull-right'  %>
                  </div>
                </div>

            <% end %>
      </div>

<style type="text/css">
  .new_form{
    width: 100%;
    float: left;
    padding-left: 10%;
    padding-top: 4%;
  }
  .actions{
        width: 49%;
    float: left;
  }
</style>

<script>
  jQuery('#numberonly').keyup(function() {
    $(this).val($(this).val().replace(/[^0-9\.]/g,''));
    // this.value = this.value.replace(/[^0-9\s]/g,'');
    // alert("please enter number only.")
  });
</script>

<script>
  jQuery('#input').keyup(function(){
    this.value = this.value.replace(/[^A-Z a-z\s\&]/g,'');
  });
</script>

<script type="text/javascript">
  var addressString = "~john smith~123 Street~Apt 4~New York~NY~12345~",
    keys = "name address1 address2 city state zipcode".split(" "),
    address = {};

// clean up the string with the first replace
// "abuse" the second replace to map the keys to the matches
addressString.replace(/^~|~$/g).replace(/[^~]+/g, function(match){
    address[ keys.unshift() ] = match;
});
</script>


<%#==========================================================================================%>
<script type="text/javascript">
      $("#textbox1").keyup(function(){
        var textinput = $('#textbox1').val().substring(0,20);
        var output = textinput.toLowerCase().replace(/\s/g, "_").replace(/[\@\!\$\&\~\)\(\|\""\:\?\#\%\-\+\;\<\>/\{\.}]/g,'').replace(/[0-9]+/g, '');
        $("#textbox2").val(output).toLowerCase().replace(/^~|~$/g).replace(/[^~]+/g);
        // $("#textbox2").val(output);
        
        
        
    });
</script>


<%#==========================================================================================%>


<script>

  $(document).ready(function () {
  $(".org_form").validate({
  debug: true,
  rules: {
  "organization[org_name]": {required: true },
  "organization[first_name]": {required: true},
  "organization[last_name]": {required: true},
  "organization[address_line1]": {required: true},
  "organization[city]": {required: true},
  "organization[state]": {required: true},
  "organization[country]": {required: true},
  "organization[zip_code]": {required: true, minlength: 6, maxlength: 6}
  },
  debug: false,
  messages: {
  "organization[org_name]": {required: "Please, enter a organization name "},
  "organization[first_name]": {required: "please, enter a first name."},
  "organization[last_name]": {required: "please, enter a last name."},
  "organization[address_line1]": {required: "please, enter a address1."},
  "organization[city]": {required: "please, enter a city."},
  "organization[state]": {required: "please, enter a state."},
  "organization[country]": {required: "please, enter a country."},
  "organization[zip_code]": {required: "Please, enter 6 digit only"},
  }
  });
  });
</script>

<script type="text/javascript">
$('#txtbox').keyup(function (e) {
    var $this = $(this);
    setTimeout(function (e) {
        if (($this.val()).match(/[^0-9]/g))
        {
            $("#errormsg").html("Only Numerical Characters allowed").show().delay(2500).fadeOut("slow");
            return false;                       
            setTimeout(function (e) {
                $this.val(null);
            },2500);
        }                   
    }, 5);
});
</script>

<style type="text/css">
#errmsg
  {
  color: red;
}
</style>

<style type="text/css">
  body {
    padding: 20px;
}

label {
    display: block;
}

input.error {
    border: 1px solid red;
}

label.error {
    font-weight: normal;
    color: red;
}

button {
    display: block;
    margin-top: 20px;
}
</style>

app/views/organizations/_table.html.erb
<div class="table_invoice">
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr class="bg-primary">
        <th class='align_center'>Id</th>
        <th class='align_center'>Org Name</th>
        <th class='align_center'>Org Identifier</th>
        <th class='align_center'>Created By</th>
        <th class='align_center'>Country</th>
        <th class='align_center'>Created At</th>
        <th class='align_center'>Updated At</th>
      </tr>
    </thead>
    <tbody>
      <% @organizations.each do |org| %>
      <tr>
        <td class="align_center">
          <%= org.id%>
        </td>
        <td class="align_center">
          <%= org.org_name %>
        </td>
        <td class="align_center">
          <%= org.org_identifier %>
        </td>
        <td class="align_center">
        <% user = User.find_by(id: org.user_id) %>
          <%= user.email %>
        </td>
        <td class="align_center">
          <%= org.country %>
        </td>
        <td class="align_center">
          <%= org.created_at.strftime('%d-%m-%y %H:%M')%>
        </td>
        <td class="align_center">
          <%= org.updated_at.strftime('%d-%m-%y %H:%M')%>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>
<div class="flickr_pagination pagination-margin">
  <%= page_entries_info @organizations %>
  <%= will_paginate @organizations, container: false %>
</div>

app/views/organizations/create.js.erb
<% if @organization.errors.empty? %>
  $('.org_form')[0].reset();
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_organization').append('<p class = "error_msg" ><%= @organization.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/organizations/index.html.erb
<div class="container">
  <%= render "action_buttons" %>
  <%= render "table" %>
</div>

app/views/organizations/index.js.erb
jQuery('#organizations').html(" 'organizations/index' )%>");
$('#pagination a').attr('data-remote', 'true');

app/views/organizations/new.html.erb
<div class="container">
	<%= render 'form'%>
</div>